#!/bin/bash
#
# chkconfig: 2345 10 10
# description: Door System Sign Service

#
# Source function library
. /etc/rc.d/init.d/functions


APP_NAME=doorsystem
APP_HOME=/usr/local/doorsystemsignservice
JAVA_HOME=/usr/local/java
PATH=$PATH:$JAVA_HOME/bin
APP_MAIN=org.capybara.dsss.DoorSystemSignService
RETVAL=0
APP_JAR=dsss.jar

start() {
        echo -n $"Starting ${APP_NAME}: "
	for i in `ls ${APP_HOME}/lib/*.jar`; do
        		APP_CLASSPATH=${APP_CLASSPATH}:${i}
	done
	APP_CLASSPATH=${APP_CLASSPATH}:${APP_JAR}
	cd ${APP_HOME}
	${APP_HOME}/bin/jsvc -wait 20 -classpath "${APP_CLASSPATH}" -Dmac=${MAC} ${APP_MAIN}
 	RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
    	echo_success
    	touch /var/lock/subsys/doorsystemsignservice
    else 
    	echo_failure
    fi
	echo
    return $RETVAL
}

stop() {
	echo -n $"Stopping ${APP_NAME}: "
	${APP_HOME}/bin/jsvc -stop ${APP_MAIN}
 	RETVAL=$?
    if [ $RETVAL -eq 0 ]; then
    	echo_success
    else 
    	echo_failure
    fi
	echo
	return $RETVAL
}

 
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status servicename
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
  
exit 0
